### ISSUE TITLE
Provider not set or invalid

### ISSUE THREAD

**Issue by ortchi42** [Sam44323/BSC-ETH-Bridge#2]
Hello :)
I am rebuilding your bridge.
Creating the contracte and the frontend was not the problem, but I have problems with the backend.
What do I have to enter in the .env for ETH_PROVIDER and BSC_PROVIDER?
info: ℹ: txHash for burning BTK on binance: 0x6f2f964cd784b4901234cf9992aa70ae54519886a7875d790c02e3619a8c8a84
error: Can't mint the tokens!: Provider not set or invalid

**Comment by Sam44323** [comment]
Hey @ortchi42, you have to add the node providers for the chains. You can use getblock to get those providers or any other services such as alchemy or infura. 

Cheers!

**Comment by ortchi42** [comment]
I have already tested Alchemy and Infura. I am currently working with getblock, but I always get the same error.
I have tried wss and https.
Maybe it's because of the syntax
ETH_PROVIDER=https://eth.getblock.io/rinkeby/?api_key=.... 
BSC_PROVIDER=https://bsc.getblock.io/testnet/?api_key=....
PRIVATE_KEY=c8a907......    //Private Key Metamask

**Comment by Sam44323** [comment]
Hey, @ortchi42  can you make sure that in web3 file you have the following code present, if not, you can copy the code snippet attached below

```
import Web3 from "web3";
import dotenv from "dotenv";

dotenv.config({
  path: ".env",
});

export const getWeb3 = (network: "ETH" | "BSC") => {
  return new Web3(
    network === "ETH"
      ? process.env.ETH_PROVIDER!
      : process.env.BSC_PROVIDER!
  );
};
```

**Comment by Sam44323** [comment]
Also make sure that you have **0x** added before your Private-key @ortchi42

**Comment by ortchi42** [comment]
I had to write the provider directly in, change the private Key ;) and i also wrote the addresses of the bridges in the .env then it worked.
THANKS!!!!!
I am testing :) Have a nice weekend!


```
import Web3 from "web3";
import dotenv from "dotenv";

dotenv.config({
path: ".env",
});

export const getWeb3 = (network: "ETH" | "BSC") => {
return new Web3(
network === "ETH"
? "https://eth.getblock.io/rinkeby/?api_key="
: "https://bsc.getblock.io/testnet/?api_key=6"
);
};
```
